### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kaypro4** [skonagaya/HTTP-Push#1]
Hello, I would like to leverage this code and adapt based on my own needs. I would submit pull requests for any discrete features that I think might be useful for the greater set of users.

Is this codebase distributed under an open source license? If so, which one?

Thanks!

**Comment by skonagaya** [comment]
Thanks for showing interest in the project! The source is under MIT licensing. I'll be streaming new features in as time permits. Happy tweaking.

Sean

**Comment by kaypro4** [comment]
Great, thanks Sean!
