### ISSUE TITLE
Are Headers possible?

### ISSUE THREAD

**Issue by HansWurst90** [skonagaya/HTTP-Push#13]
Hi,
thank you for developing such a useful app!
I want to us the app to control some lights and power sockets in my home.
The command to switch them on is
`curl -X PUT http://127.0.0.1:51826/characteristics --header "Content-Type:Application/json" --header "authorization: XXX-XX-XXX" --data "{ \"characteristics\": [{ \"aid\": 2, \"iid\": 9, \"value\": 0}] }"`
I the App I can see the option for PUT and also the possibility to add data via json.
Is there a way to send the authorization-Header too?
Thank's in advance.

Jan

**Comment by skonagaya** [comment]
No headers for now. In the meantime, you can authenticate using using parameters in your method calls. You'd have to update your back-end code as well.

`curl -X PUT http://127.0.0.1:51826/characteristics?id=xxx-xxx&key=xxx-xxx --header "Content-Type:Application/json" --data "{ \"characteristics\": [{ \"aid\": 2, \"iid\": 9, \"value\": 0}] `

**Comment by HansWurst90** [comment]
Unfortunately I didn't write the back-end myself. The URL is the way you can [control Homebridge via URL](https://github.com/nfarina/homebridge/issues/506).
Is there a way for me to hardcode the headers in every request and have a modified version of your app on my Pebble?

[edit]
[Here](https://github.com/skonagaya/HTTP-Push/blob/1e8e0e5a821a78f2ba24ac1a88144b78b9ca13e3/src/js/pebble-js-app.js#L18) for example?

**Comment by skonagaya** [comment]
Sure, you can hard code it in _pebble-js-app.js_:

```
xhr.open(method, ToUrl);
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.setRequestHeader('Authorization', 'xxxxxxxxxxxxxxxxxxxxxx');
xhr.send(withJson);
```

**Comment by HansWurst90** [comment]
It worked.
Thank you a lot!
