### ISSUE TITLE
JSON POST not working

### ISSUE THREAD

**Issue by paviro** [skonagaya/HTTP-Push#14]
I just tried to add some Home Assistant toggles to HTTP Push. It failed and always gave me an error.
In order to debug the issue I tried sending the request on my computer the way you do in your code, it failed with an internal server error. Sending the JSON data as a string by adding `JSON.stringify` seems to fix it... Any ideas?

```
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
		document.body.appendChild( document.createTextNode(xhr.responseText) );
};
xhr.open("POST", "http://xxxx:8123/api/services/switch/toggle?api_password=xyz");
xhr.setRequestHeader('Content-Type', 'application/json');
payload = JSON.stringify({"entity_id": "switch.verstarker"})
xhr.send(payload);
```

https://github.com/skonagaya/HTTP-Push/blob/master/src/js/pebble-js-app.js#L19

**Comment by skonagaya** [comment]
You're referencing the code for PUT. The POST code is a few lines down [line 42](https://github.com/skonagaya/HTTP-Push/blob/master/src/js/pebble-js-app.js#L42).

In the HTTP Push app, try configuring a POST with only the Endpoint URL `http://xxxx:8123/api/services/switch/toggle` and enter this in the JSON field `{"api_password":"xyz","entity_id":"switch.verstarker"}`. 

The code for the POST (line 42) actually breaks out the JSON content into a query string. So in our case, it'll generate the following request URL `http://xxxx:8123/api/services/switch/toggle?api_password=xyz&entity_id=switch.verstarker`. And the content-type header will be `application/x-www-form-urlencoded` 

-Sean

**Comment by paviro** [comment]
This does not seem to work with Home Assistant... :/ 
Any chance real json posting will be added? Or is there a reason it is not?

**Comment by skonagaya** [comment]
It's one of the items that was on the roadmap for future release.

-Sean

**Comment by skonagaya** [comment]
@paviro Sorry about that bummer. I'll bump this up and try to have a release pushed out to fix this soon.

-Sean

**Comment by paviro** [comment]
Thank you Sean that would be amazing! If there is a way I can help let me know :) never done any Pebble related work yet but I worked on JS projects before.

Of topic question: Is it normal that the app has no icon on the watch?

**Comment by skonagaya** [comment]
Thanks Pav. I keep this repo up-to-date with all the releases so you're more than welcome to contribute. I tend to use pull requests to see checkout what goes into a release and what doesn't. It's hard to get motivated to support Pebble apps these days with the acquisitions and whatnot. 

To answer your question, I didn't notice that there's no icon on the watch. Nice catch!

**Comment by paviro** [comment]
Any tips / links on how to get started with pebble development with the Linux/Mac SDK you liked? :)

**Comment by skonagaya** [comment]
[This video](https://youtu.be/TtP7z6wceqI) is all I needed to get started. It builds a simple app from start to finish in a Linux environment. I only go back to online docs when I needed it; Most of the questions I had were answered on stackoverflow as usual.

If I can do this all over again, I'd go use Pebble.js instead of C.

Good luck!

**Comment by paviro** [comment]
But doesn’t pebble js use way more battery power since the views are rendered on the phone?

**Comment by skonagaya** [comment]
Ah, I didn't know that. It also looks like PebbleJS has limited Watch API access. I retract my statement, C is the way to go! 

I was just remembering the painfully large amount of time troubleshooting memory leaks. Segfaults are a nightmare to troubleshoot.

**Comment by paviro** [comment]
Didn’t read much but I think it is a small c app running on the watch and the js code running on the phone. 
So if you for example press a button in your watch interface it sends the event to the phone and the phone sends back the new UI.

**Comment by skonagaya** [comment]
Great news @paviro !

A new release has been pushed out to address this issue. You can now select a content-type when configuring a request. Alternatively, you can specify a custom header.

![kakaotalk_2017-08-11-19-03-01_photo_85](https://user-images.githubusercontent.com/1175459/29236906-d2d867d6-7ec7-11e7-9ef0-b2e664def1b8.jpeg)

**Comment by paviro** [comment]
That’s awesome thank you!

**Comment by paviro** [comment]
Just wanted to thank you again! :) Started using your App with Home Assistant again yesterday and it’s great!

**Comment by skonagaya** [comment]
I'm glad to hear you got things working. 

I also started using Home Assistant myself. I love it!
