### ISSUE TITLE
Lost config data since recent update

### ISSUE THREAD

**Issue by mriffault** [skonagaya/HTTP-Push#19]
Hi,
All my folders and requests disappeared from the settings form since a recent update (I guess the one which includes the config export/import). I can see them on the watch but can't administer it anymore through the config form, and the queries are not functioning anymore :'(
Is there a way to get the config back into the app?
Thanks

**Comment by skonagaya** [comment]
Unfortunately the only way to recover data is by saving configuration via the import/export function. This was designed to give users full control of the fate of incidents.

The good news is that the app does not care to keep track of your data, where I believe IoT in the current state, have leaned too much in favor of convenience over security. 

-Sean
